//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECRWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEmail
    {
        public int EmployeeEmailId { get; set; }
        public int EmployeeId { get; set; }
        public byte EmailTypeId { get; set; }
        public string Email { get; set; }
        public byte RecordStatusId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
